[package]
name = "vivace-autoload"
description = "Composer-compatible autoloader generation for vivace"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
vivace-core = { path = "../vivace-core" }
serde_json.workspace = true
thiserror.workspace = true
md-5.workspace = true
pcre2.workspace = true
walkdir.workspace = true
base64.workspace = true
sha1.workspace = true

[dev-dependencies]
tempfile.workspace = true
